# Generated by Django 4.1.7 on 2023-03-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_blogpost_post_author_alter_comment_blog_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="post_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_author",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
